project "pdfium"

dofile(_BUILD_DIR .. "/static_library.lua")

configuration { "*" }

uuid "5149C8A4-ADEA-47BD-BD79-BA7A8C5B0A89"

flags { "NoPCH" }

includedirs {
  ".",
  _3RDPARTY_DIR,
  _3RDPARTY_DIR .. "/abseil-cpp",
  _3RDPARTY_DIR .. "/fast_float/include",
  _3RDPARTY_DIR .. "/freetype/include",
  _3RDPARTY_DIR .. "/icu/icu4c/source/common",
  _3RDPARTY_DIR .. "/libjpeg-turbo",
  _3RDPARTY_DIR .. "/openjpeg/src/lib/openjp2",
  _3RDPARTY_DIR .. "/zlib-ng",
}

defines {
  "USE_SYSTEM_ICUUC",
  "USE_SYSTEM_LIBJPEG",
  "USE_SYSTEM_LIBOPENJPEG2",
  "USE_SYSTEM_ZLIB",
}

files {
  "core/fdrm/fx_crypt_aes.cpp",
  "core/fdrm/fx_crypt.cpp",
  "core/fdrm/fx_crypt_sha.cpp",
  "core/fpdfapi/cmaps/**/*.cpp",
  "core/fpdfapi/cmaps/fpdf_cmaps.cpp",
  "core/fpdfapi/edit/cpdf_contentstream_write_utils.cpp",
  "core/fpdfapi/font/cfx_cttgsubtable.cpp",
  "core/fpdfapi/font/cfx_stockfontarray.cpp",
  "core/fpdfapi/font/cpdf_cid2unicodemap.cpp",
  "core/fpdfapi/font/cpdf_cidfont.cpp",
  "core/fpdfapi/font/cpdf_cmap.cpp",
  "core/fpdfapi/font/cpdf_cmapparser.cpp",
  "core/fpdfapi/font/cpdf_font.cpp",
  "core/fpdfapi/font/cpdf_fontencoding.cpp",
  "core/fpdfapi/font/cpdf_fontglobals.cpp",
  "core/fpdfapi/font/cpdf_simplefont.cpp",
  "core/fpdfapi/font/cpdf_tounicodemap.cpp",
  "core/fpdfapi/font/cpdf_truetypefont.cpp",
  "core/fpdfapi/font/cpdf_type1font.cpp",
  "core/fpdfapi/font/cpdf_type3char.cpp",
  "core/fpdfapi/font/cpdf_type3font.cpp",
  "core/fpdfapi/page/cpdf_allstates.cpp",
  "core/fpdfapi/page/cpdf_annotcontext.cpp",
  "core/fpdfapi/page/cpdf_basedcs.cpp",
  "core/fpdfapi/page/cpdf_clippath.cpp",
  "core/fpdfapi/page/cpdf_color.cpp",
  "core/fpdfapi/page/cpdf_colorspace.cpp",
  "core/fpdfapi/page/cpdf_colorstate.cpp",
  "core/fpdfapi/page/cpdf_contentmarkitem.cpp",
  "core/fpdfapi/page/cpdf_contentmarks.cpp",
  "core/fpdfapi/page/cpdf_contentparser.cpp",
  "core/fpdfapi/page/cpdf_devicecs.cpp",
  "core/fpdfapi/page/cpdf_dib.cpp",
  "core/fpdfapi/page/cpdf_docpagedata.cpp",
  "core/fpdfapi/page/cpdf_expintfunc.cpp",
  "core/fpdfapi/page/cpdf_form.cpp",
  "core/fpdfapi/page/cpdf_formobject.cpp",
  "core/fpdfapi/page/cpdf_function.cpp",
  "core/fpdfapi/page/cpdf_generalstate.cpp",
  "core/fpdfapi/page/cpdf_graphicstates.cpp",
  "core/fpdfapi/page/cpdf_iccprofile.cpp",
  "core/fpdfapi/page/cpdf_image.cpp",
  "core/fpdfapi/page/cpdf_imageloader.cpp",
  "core/fpdfapi/page/cpdf_imageobject.cpp",
  "core/fpdfapi/page/cpdf_indexedcs.cpp",
  "core/fpdfapi/page/cpdf_meshstream.cpp",
  "core/fpdfapi/page/cpdf_occontext.cpp",
  "core/fpdfapi/page/cpdf_page.cpp",
  "core/fpdfapi/page/cpdf_pageimagecache.cpp",
  "core/fpdfapi/page/cpdf_pagemodule.cpp",
  "core/fpdfapi/page/cpdf_pageobject.cpp",
  "core/fpdfapi/page/cpdf_pageobjectholder.cpp",
  "core/fpdfapi/page/cpdf_path.cpp",
  "core/fpdfapi/page/cpdf_pathobject.cpp",
  "core/fpdfapi/page/cpdf_pattern.cpp",
  "core/fpdfapi/page/cpdf_patterncs.cpp",
  "core/fpdfapi/page/cpdf_psengine.cpp",
  "core/fpdfapi/page/cpdf_psfunc.cpp",
  "core/fpdfapi/page/cpdf_sampledfunc.cpp",
  "core/fpdfapi/page/cpdf_shadingobject.cpp",
  "core/fpdfapi/page/cpdf_shadingpattern.cpp",
  "core/fpdfapi/page/cpdf_stitchfunc.cpp",
  "core/fpdfapi/page/cpdf_streamcontentparser.cpp",
  "core/fpdfapi/page/cpdf_streamparser.cpp",
  "core/fpdfapi/page/cpdf_textobject.cpp",
  "core/fpdfapi/page/cpdf_textstate.cpp",
  "core/fpdfapi/page/cpdf_tilingpattern.cpp",
  "core/fpdfapi/page/cpdf_transferfunc.cpp",
  "core/fpdfapi/page/cpdf_transferfuncdib.cpp",
  "core/fpdfapi/page/cpdf_transparency.cpp",
  "core/fpdfapi/page/jpx_decode_conversion.cpp",
  "core/fpdfapi/parser/cfdf_document.cpp",
  "core/fpdfapi/parser/cpdf_array.cpp",
  "core/fpdfapi/parser/cpdf_boolean.cpp",
  "core/fpdfapi/parser/cpdf_cross_ref_table.cpp",
  "core/fpdfapi/parser/cpdf_crypto_handler.cpp",
  "core/fpdfapi/parser/cpdf_dictionary.cpp",
  "core/fpdfapi/parser/cpdf_document.cpp",
  "core/fpdfapi/parser/cpdf_encryptor.cpp",
  "core/fpdfapi/parser/cpdf_flateencoder.cpp",
  "core/fpdfapi/parser/cpdf_indirect_object_holder.cpp",
  "core/fpdfapi/parser/cpdf_linearized_header.cpp",
  "core/fpdfapi/parser/cpdf_name.cpp",
  "core/fpdfapi/parser/cpdf_null.cpp",
  "core/fpdfapi/parser/cpdf_number.cpp",
  "core/fpdfapi/parser/cpdf_object.cpp",
  "core/fpdfapi/parser/cpdf_object_stream.cpp",
  "core/fpdfapi/parser/cpdf_object_walker.cpp",
  "core/fpdfapi/parser/cpdf_parser.cpp",
  "core/fpdfapi/parser/cpdf_read_validator.cpp",
  "core/fpdfapi/parser/cpdf_reference.cpp",
  "core/fpdfapi/parser/cpdf_security_handler.cpp",
  "core/fpdfapi/parser/cpdf_simple_parser.cpp",
  "core/fpdfapi/parser/cpdf_stream_acc.cpp",
  "core/fpdfapi/parser/cpdf_stream.cpp",
  "core/fpdfapi/parser/cpdf_string.cpp",
  "core/fpdfapi/parser/cpdf_syntax_parser.cpp",
  "core/fpdfapi/parser/fpdf_parser_decode.cpp",
  "core/fpdfapi/parser/fpdf_parser_utility.cpp",
  "core/fpdfapi/render/charposlist.cpp",
  "core/fpdfapi/render/cpdf_devicebuffer.cpp",
  "core/fpdfapi/render/cpdf_docrenderdata.cpp",
  "core/fpdfapi/render/cpdf_imagerenderer.cpp",
  "core/fpdfapi/render/cpdf_pagerendercontext.cpp",
  "core/fpdfapi/render/cpdf_progressiverenderer.cpp",
  "core/fpdfapi/render/cpdf_rendercontext.cpp",
  "core/fpdfapi/render/cpdf_renderoptions.cpp",
  "core/fpdfapi/render/cpdf_rendershading.cpp",
  "core/fpdfapi/render/cpdf_renderstatus.cpp",
  "core/fpdfapi/render/cpdf_rendertiling.cpp",
  "core/fpdfapi/render/cpdf_scaledrenderbuffer.cpp",
  "core/fpdfapi/render/cpdf_textrenderer.cpp",
  "core/fpdfapi/render/cpdf_type3cache.cpp",
  "core/fpdfapi/render/cpdf_type3glyphmap.cpp",
  "core/fpdfdoc/cpdf_aaction.cpp",
  "core/fpdfdoc/cpdf_action.cpp",
  "core/fpdfdoc/cpdf_annot.cpp",
  "core/fpdfdoc/cpdf_annotlist.cpp",
  "core/fpdfdoc/cpdf_apsettings.cpp",
  "core/fpdfdoc/cpdf_bafontmap.cpp",
  "core/fpdfdoc/cpdf_color_utils.cpp",
  "core/fpdfdoc/cpdf_defaultappearance.cpp",
  "core/fpdfdoc/cpdf_dest.cpp",
  "core/fpdfdoc/cpdf_filespec.cpp",
  "core/fpdfdoc/cpdf_formcontrol.cpp",
  "core/fpdfdoc/cpdf_formfield.cpp",
  "core/fpdfdoc/cpdf_generateap.cpp",
  "core/fpdfdoc/cpdf_icon.cpp",
  "core/fpdfdoc/cpdf_iconfit.cpp",
  "core/fpdfdoc/cpdf_interactiveform.cpp",
  "core/fpdfdoc/cpdf_metadata.cpp",
  "core/fpdfdoc/cpdf_nametree.cpp",
  "core/fpdfdoc/cpdf_viewerpreferences.cpp",
  "core/fpdfdoc/cpvt_fontmap.cpp",
  "core/fpdfdoc/cpvt_section.cpp",
  "core/fpdfdoc/cpvt_variabletext.cpp",
  "core/fpdfdoc/cpvt_wordinfo.cpp",
  "core/fxcodec/basic/basicmodule.cpp",
  "core/fxcodec/data_and_bytes_consumed.cpp",
  "core/fxcodec/fax/faxmodule.cpp",
  "core/fxcodec/flate/flatemodule.cpp",
  "core/fxcodec/fx_codec.cpp",
  "core/fxcodec/icc/icc_transform.cpp",
  "core/fxcodec/jbig2/JBig2_ArithDecoder.cpp",
  "core/fxcodec/jbig2/JBig2_ArithIntDecoder.cpp",
  "core/fxcodec/jbig2/JBig2_BitStream.cpp",
  "core/fxcodec/jbig2/JBig2_Context.cpp",
  "core/fxcodec/jbig2/jbig2_decoder.cpp",
  "core/fxcodec/jbig2/JBig2_DocumentContext.cpp",
  "core/fxcodec/jbig2/JBig2_GrdProc.cpp",
  "core/fxcodec/jbig2/JBig2_GrrdProc.cpp",
  "core/fxcodec/jbig2/JBig2_HtrdProc.cpp",
  "core/fxcodec/jbig2/JBig2_HuffmanDecoder.cpp",
  "core/fxcodec/jbig2/JBig2_HuffmanTable.cpp",
  "core/fxcodec/jbig2/JBig2_Image.cpp",
  "core/fxcodec/jbig2/JBig2_PatternDict.cpp",
  "core/fxcodec/jbig2/JBig2_PddProc.cpp",
  "core/fxcodec/jbig2/JBig2_SddProc.cpp",
  "core/fxcodec/jbig2/JBig2_Segment.cpp",
  "core/fxcodec/jbig2/JBig2_SymbolDict.cpp",
  "core/fxcodec/jbig2/JBig2_TrdProc.cpp",
  "core/fxcodec/jpeg/jpeg_common.c",
  "core/fxcodec/jpeg/jpegmodule.cpp",
  "core/fxcodec/jpx/cjpx_decoder.cpp",
  "core/fxcodec/jpx/jpx_decode_utils.cpp",
  "core/fxcodec/scanlinedecoder.cpp",
  "core/fxcrt/binary_buffer.cpp",
  "core/fxcrt/bytestring.cpp",
  "core/fxcrt/cfx_bitstream.cpp",
  "core/fxcrt/cfx_read_only_span_stream.cpp",
  "core/fxcrt/cfx_read_only_vector_stream.cpp",
  "core/fxcrt/cfx_seekablestreamproxy.cpp",
  "core/fxcrt/cfx_timer.cpp",
  "core/fxcrt/debug/alias.cc",
  "core/fxcrt/fx_codepage.cpp",
  "core/fxcrt/fx_coordinates.cpp",
  "core/fxcrt/fx_extension.cpp",
  "core/fxcrt/fx_memory.cpp",
  "core/fxcrt/fx_memory_malloc.cpp",
  "core/fxcrt/fx_number.cpp",
  "core/fxcrt/fx_random.cpp",
  "core/fxcrt/fx_stream.cpp",
  "core/fxcrt/fx_string.cpp",
  "core/fxcrt/fx_system.cpp",
  "core/fxcrt/observed_ptr.cpp",
  "core/fxcrt/string_data_template.cpp",
  "core/fxcrt/string_template.cpp",
  "core/fxcrt/widestring.cpp",
  "core/fxcrt/xml/cfx_xmlchardata.cpp",
  "core/fxcrt/xml/cfx_xmldocument.cpp",
  "core/fxcrt/xml/cfx_xmlelement.cpp",
  "core/fxcrt/xml/cfx_xmlinstruction.cpp",
  "core/fxcrt/xml/cfx_xmlnode.cpp",
  "core/fxcrt/xml/cfx_xmlparser.cpp",
  "core/fxcrt/xml/cfx_xmltext.cpp",
  "core/fxge/agg/cfx_agg_bitmapcomposer.cpp",
  "core/fxge/agg/cfx_agg_cliprgn.cpp",
  "core/fxge/agg/cfx_agg_devicedriver.cpp",
  "core/fxge/agg/cfx_agg_imagerenderer.cpp",
  "core/fxge/calculate_pitch.cpp",
  "core/fxge/cfx_color.cpp",
  "core/fxge/cfx_defaultrenderdevice.cpp",
  "core/fxge/cfx_drawutils.cpp",
  "core/fxge/cfx_face.cpp",
  "core/fxge/cfx_folderfontinfo.cpp",
  "core/fxge/cfx_fontcache.cpp",
  "core/fxge/cfx_font.cpp",
  "core/fxge/cfx_fontmapper.cpp",
  "core/fxge/cfx_fontmgr.cpp",
  "core/fxge/cfx_gemodule.cpp",
  "core/fxge/cfx_glyphbitmap.cpp",
  "core/fxge/cfx_glyphcache.cpp",
  "core/fxge/cfx_graphstate.cpp",
  "core/fxge/cfx_graphstatedata.cpp",
  "core/fxge/cfx_path.cpp",
  "core/fxge/cfx_renderdevice.cpp",
  "core/fxge/cfx_substfont.cpp",
  "core/fxge/cfx_unicodeencoding.cpp",
  "core/fxge/dib/blend.cpp",
  "core/fxge/dib/cfx_bitmapstorer.cpp",
  "core/fxge/dib/cfx_cmyk_to_srgb.cpp",
  "core/fxge/dib/cfx_dibbase.cpp",
  "core/fxge/dib/cfx_dibitmap.cpp",
  "core/fxge/dib/cfx_imagestretcher.cpp",
  "core/fxge/dib/cfx_imagetransformer.cpp",
  "core/fxge/dib/cfx_scanlinecompositor.cpp",
  "core/fxge/dib/cstretchengine.cpp",
  "core/fxge/dib/fx_dib.cpp",
  "core/fxge/fontdata/chromefontdata/*.cpp",
  "core/fxge/freetype/fx_freetype.cpp",
  "core/fxge/fx_font.cpp",
  "core/fxge/renderdevicedriver_iface.cpp",
  "core/fxge/scoped_font_transform.cpp",
  "core/fxge/text_char_pos.cpp",
  "core/fxge/text_glyph_pos.cpp",
  "fpdfsdk/cpdfsdk_annot.cpp",
  "fpdfsdk/cpdfsdk_annotiteration.cpp",
  "fpdfsdk/cpdfsdk_annotiterator.cpp",
  "fpdfsdk/cpdfsdk_appstream.cpp",
  "fpdfsdk/cpdfsdk_baannot.cpp",
  "fpdfsdk/cpdfsdk_customaccess.cpp",
  "fpdfsdk/cpdfsdk_formfillenvironment.cpp",
  "fpdfsdk/cpdfsdk_helpers.cpp",
  "fpdfsdk/cpdfsdk_interactiveform.cpp",
  "fpdfsdk/cpdfsdk_pageview.cpp",
  "fpdfsdk/cpdfsdk_renderpage.cpp",
  "fpdfsdk/cpdfsdk_widget.cpp",
  "fpdfsdk/formfiller/cffl_button.cpp",
  "fpdfsdk/formfiller/cffl_checkbox.cpp",
  "fpdfsdk/formfiller/cffl_combobox.cpp",
  "fpdfsdk/formfiller/cffl_fieldaction.cpp",
  "fpdfsdk/formfiller/cffl_formfield.cpp",
  "fpdfsdk/formfiller/cffl_interactiveformfiller.cpp",
  "fpdfsdk/formfiller/cffl_listbox.cpp",
  "fpdfsdk/formfiller/cffl_perwindowdata.cpp",
  "fpdfsdk/formfiller/cffl_pushbutton.cpp",
  "fpdfsdk/formfiller/cffl_radiobutton.cpp",
  "fpdfsdk/formfiller/cffl_textfield.cpp",
  "fpdfsdk/formfiller/cffl_textobject.cpp",
  "fpdfsdk/fpdf_view.cpp",
  "fpdfsdk/pwl/cpwl_button.cpp",
  "fpdfsdk/pwl/cpwl_caret.cpp",
  "fpdfsdk/pwl/cpwl_cbbutton.cpp",
  "fpdfsdk/pwl/cpwl_cblistbox.cpp",
  "fpdfsdk/pwl/cpwl_combo_box.cpp",
  "fpdfsdk/pwl/cpwl_edit.cpp",
  "fpdfsdk/pwl/cpwl_edit_impl.cpp",
  "fpdfsdk/pwl/cpwl_list_box.cpp",
  "fpdfsdk/pwl/cpwl_list_ctrl.cpp",
  "fpdfsdk/pwl/cpwl_sbbutton.cpp",
  "fpdfsdk/pwl/cpwl_scroll_bar.cpp",
  "fpdfsdk/pwl/cpwl_special_button.cpp",
  "fpdfsdk/pwl/cpwl_wnd.cpp",
  "fxjs/cjs_event_context_stub.cpp",
  "fxjs/cjs_runtimestub.cpp",
  "fxjs/ijs_runtime.cpp",
  "third_party/agg23/agg_curves.cpp",
  "third_party/agg23/agg_path_storage.cpp",
  "third_party/agg23/agg_rasterizer_scanline_aa.cpp",
  "third_party/agg23/agg_vcgen_dash.cpp",
  "third_party/agg23/agg_vcgen_stroke.cpp",
  "third_party/lcms/src/cmsalpha.c",
  "third_party/lcms/src/cmscnvrt.c",
  "third_party/lcms/src/cmserr.c",
  "third_party/lcms/src/cmsgamma.c",
  "third_party/lcms/src/cmsgmt.c",
  "third_party/lcms/src/cmshalf.c",
  "third_party/lcms/src/cmsintrp.c",
  "third_party/lcms/src/cmsio0.c",
  "third_party/lcms/src/cmsio1.c",
  "third_party/lcms/src/cmslut.c",
  "third_party/lcms/src/cmsmtrx.c",
  "third_party/lcms/src/cmsnamed.c",
  "third_party/lcms/src/cmsopt.c",
  "third_party/lcms/src/cmspack.c",
  "third_party/lcms/src/cmspcs.c",
  "third_party/lcms/src/cmsplugin.c",
  "third_party/lcms/src/cmssamp.c",
  "third_party/lcms/src/cmstypes.c",
  "third_party/lcms/src/cmsvirt.c",
  "third_party/lcms/src/cmswtpnt.c",
  "third_party/lcms/src/cmsxform.c",
}

-- unix based platforms
if not (_PLATFORM_WINDOWS) then
  files {
    "core/fxcrt/cfx_fileaccess_posix.cpp",
    "core/fxcrt/fx_folder_posix.cpp",
  }
end

if (_PLATFORM_ANDROID) then
  files {
    "core/fxge/android/cfpf_skiadevicemodule.cpp",
    "core/fxge/android/cfpf_skiafont.cpp",
    "core/fxge/android/cfpf_skiafontmgr.cpp",
    "core/fxge/android/cfpf_skiapathfont.cpp",
    "core/fxge/android/cfx_androidfontinfo.cpp",
    "core/fxge/android/fx_android_impl.cpp",
  }

  configuration { "*release" }

  buildoptions {
    "-O3",
  }
end

if (_PLATFORM_IOS) then
  files {
    "core/fxge/apple/fx_apple_impl.cpp",
    "core/fxge/apple/fx_apple_platform.cpp",
    "core/fxge/apple/fx_quartz_device.cpp",
  }

  configuration { "*release" }

  buildoptions {
    "-O3",
  }
end

if (_PLATFORM_LINUX) then
  files {
    "core/fxge/linux/fx_linux_impl.cpp",
  }
end

if (_PLATFORM_MACOS) then
  files {
    "core/fxge/apple/fx_apple_impl.cpp",
    "core/fxge/apple/fx_apple_platform.cpp",
    "core/fxge/apple/fx_quartz_device.cpp",
  }
end

if (_PLATFORM_WINDOWS) then
  files {
    "core/fpdfapi/render/cpdf_windowsrenderdevice.cpp",
    "core/fxcrt/cfx_fileaccess_windows.cpp",
    "core/fxcrt/code_point_view.cpp",
    "core/fxcrt/fx_folder_windows.cpp",
    "core/fxcrt/win/win_util.cc",
    "core/fxge/cfx_windowsrenderdevice.cpp",
    "core/fxge/win32/cfx_psfonttracker.cpp",
    "core/fxge/win32/cfx_psrenderer.cpp",
    "core/fxge/win32/cgdi_device_driver.cpp",
    "core/fxge/win32/cgdi_display_driver.cpp",
    "core/fxge/win32/cgdi_plus_ext.cpp",
    "core/fxge/win32/cgdi_printer_driver.cpp",
    "core/fxge/win32/cps_printer_driver.cpp",
    "core/fxge/win32/cpsoutput.cpp",
    "core/fxge/win32/ctext_only_printer_driver.cpp",
    "core/fxge/win32/cwin32_platform.cpp",
  }
end
